(part "SN65HVD234QDRQ1"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "TXD") (portType OUTPUT))
        (port "2" (symbPinId 2) (portName "GND") (portType GROUND))
        (port "3" (symbPinId 3) (portName "VCC") (portType POWER))
        (port "4" (symbPinId 4) (portName "RXD") (portType INPUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INPUT))
        (port "6" (symbPinId 6) (portName "CANL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CANH") (portType INOUT))
        (port "8" (symbPinId 8) (portName "RS") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "595-SN65HVD234QDRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/SN65HVD234QDRQ1?qs=vxeUf0TWHS1ncTjp6RJM2A%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "SN65HVD234QDRQ1")
    (property "Description" "3.3-V Automotive CAN Bus Transceivers")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/sn65hvd234-q1")
    (property "symbolName1" "SN65HVD234QDRQ1")
)
