(part "MMBT3906LT3G"
    (packageRef "SOT96P237X111-3N")
    (interface
        (port "1" (symbPinId 1) (portName "B") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "863-MMBT3906LT3G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/MMBT3906LT3G?qs=HVbQlW5zcXX6Jyx0WYl8Eg%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MMBT3906LT3G")
    (property "Description" "These Devices are Pb-Free, Halogen Free/BFR Free and are RoHS Compliant; S Prefix for Automotive and Other Applications Requiring Unique Site and Control Change Requirements; AEC-Q101 Qualified and PPAP Capable")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/MMBT3906LT1-D.PDF")
    (property "symbolName1" "MMBT3906LT3G")
)
