(part "BLM15EX121SN1D"
    (packageRef "NFZ15SG152SN10B")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "81-BLM15EX121SN1D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/BLM15EX121SN1D?qs=Ih85XBhZ45kLNeeYpXlvvg%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "BLM15EX121SN1D")
    (property "Description" "BLM15_N1D Series EMI Suppression Filter 120+/-25% at 100MHz 1.8A @85")
    (property "Datasheet_Link" "http://www.murata.com/~/media/webrenewal/support/library/catalog/products/emc/emifil/c31e.ashx?la=en-gb")
    (property "symbolName1" "BLM15EX121SN1D")
)
