(part "GRM1555C1H6R8CA01D"
    (packageRef "CAPC1005X70N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "81-GRM1555C1H6R8CA1D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/GRM1555C1H6R8CA01D?qs=q312vENifzChk4Wux6WqXA%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "GRM1555C1H6R8CA01D")
    (property "Description" "Murata 0402 GRM 6.8pF Ceramic Multilayer Capacitor, 50 V dc, +125C, C0G Dielectric, +/-0.25pF")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/A01X/G101/ENG/GRM1555C1H6R8CA01-01A.pdf")
    (property "symbolName1" "GRM1555C1H6R8CA01D")
)
