(part "DMG1012T-7"
    (packageRef "SOT50P160X90-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "621-DMG1012T-7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/DMG1012T-7?qs=vIZ3oKQCLxoEnfyeB0HcGQ%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "DMG1012T-7")
    (property "Description" "MOSFET N-Channel 20V 0.63A SOT523 Diodes Inc DMG1012T-7 N-channel MOSFET Transistor, 0.63 A, 20 V, 3-Pin SOT-523")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/DMG1012T.pdf")
    (property "symbolName1" "DMG1012T-7")
)
