(part "LQM2HPN4R7MG0L"
    (packageRef "LQM2HPN1R0MG0L")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "81-LQM2HPN4R7MG0L")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/LQM2HPN4R7MG0L?qs=%2F%252BYoplLUB5jnkqM2%2FFTc3g%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "LQM2HPN4R7MG0L")
    (property "Description" "Inductor SMD 1008 shielded 4.7uH Murata LQM2HP_G0 Series 4700 nH +/-20% Ferrite Multilayer SMD Inductor, 1008 Case, SRF: 0.025GHz 1.1A dc 138m Rdc")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02/JELF243B-0019.pdf")
    (property "symbolName1" "LQM2HPN4R7MG0L")
)
