(part "CC1206KKX7RDBB102"
    (packageRef "CAPC3216X145N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "603-CC206KKX7RDBB102")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/CC1206KKX7RDBB102?qs=vTakOoo5QyK%2FBV1e3XHXiQ%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "CC1206KKX7RDBB102")
    (property "Description" "YAGEO - CC1206KKX7RDBB102 - SMD Multilayer Ceramic Capacitor, 1000 pF, 2 kV, 1206 [3216 Metric], +/- 10%, X7R, CC Series")
    (property "Datasheet_Link" "https://www.yageo.com/upload/media/product/productsearch/datasheet/mlcc/UPY-NP0X7R_HV_500V-to-3KV_15.pdf")
    (property "symbolName1" "CC1206KKX7RDBB102")
)
