(part "RC0402FR-07432KL"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "RC0402FR-07432KL")
    (property "Description" "YAGEO (PHYCOMP) RC0402F")
    (property "Datasheet_Link" "http://www.yageo.com/documents/recent/PYu-RC0402_51_RoHS_L_6_r.pdf")
    (property "symbolName1" "RC0402FR-07432KL")
)
