(part "T520B337M2R5ATE070"
    (packageRef "T520B")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "80-T520B337M2R5ATE70")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KEMET/T520B337M2R5ATE070?qs=VVXJgp%252Bqni1pPGbucfoyFw%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "T520B337M2R5ATE070")
    (property "Description" "SMD, Polymer, Molded, Low ESR, Non-Combustible")
    (property "Datasheet_Link" "https://www.yageogroup.com/content/datasheet/asset/file/KEM_T2076_T52X-530")
    (property "symbolName1" "T520B337M2R5ATE070")
)
