(part "INA226AQDGSRQ1"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A0") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ALERT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SDA") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SCL") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VBUS") (portType INOUT))
        (port "9" (symbPinId 9) (portName "IN-") (portType INOUT))
        (port "10" (symbPinId 10) (portName "IN+") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-INA226AQDGSRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/INA226AQDGSRQ1?qs=uNh9J9Y3wTf1B1%2FBFFp7SA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "INA226AQDGSRQ1")
    (property "Description" "AEC-Q100, 36V, Bi-Directional, High Accuracy, Low-/High-Side, I2C Out Current/Power Monitor w/Alert")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/ina226-q1")
    (property "symbolName1" "INA226AQDGSRQ1")
)
