(part "TPD4E1U06DBVR"
    (packageRef "SOT95P280X145-6N")
    (interface
        (port "1" (symbPinId 1) (portName "D1+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D2+") (portType INOUT))
        (port "4" (symbPinId 4) (portName "D2-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D1-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPD4E1U06DBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPD4E1U06DBVR?qs=%2FCrDlo5IrVMRcCeY4Dk4aQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPD4E1U06DBVR")
    (property "Description" "Quad High Speed ESD Protection SOT-23-6 Texas Instruments TPD4E1U06DBVR Quad Uni-Directional ESD Protection Array, 45W peak, 6-Pin SOT-23")
    (property "Datasheet_Link" "http://www.ti.com/lit/ds/symlink/tpd4e1u06.pdf")
    (property "symbolName1" "TPD4E1U06DBVR")
)
