(part "TLV62569DBVT"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "EN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SW") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VIN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "FB") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TLV62569DBVT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TLV62569DBVT?qs=0C8XhJW8e4qp9%2F3ZjhGIMQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TLV62569DBVT")
    (property "Description" "2.5V-5.5V input, 2-A high efficiency step-down buck converter in SOT23 and SOT563 package")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TLV62569")
    (property "symbolName1" "TLV62569DBVT")
)
