(part "RC0402FR-0727RL"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "603-RC0402FR-0727RL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/RC0402FR-0727RL?qs=UOUeRUa%252B8Wlb37UyFHw9Bw%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "RC0402FR-0727RL")
    (property "Description" "27 Ohms +/-1% 0.063W, 1/16W Chip Resistor 0402 (1005 Metric) Moisture Resistant Thick Film ,-55C ~ 155C")
    (property "Datasheet_Link" "https://www.yageogroup.com/content/datasheet/asset/file/PYU-RC_GROUP_51_ROHS_L")
    (property "symbolName1" "RC0402FR-0727RL")
)
