(part "CC0402JRNPO9BN101"
    (packageRef "CAPC1005X55N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "603-CC402JRNPO9BN101")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/CC0402JRNPO9BN101?qs=AgBp2OyFlx996m5MagFg3g%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "CC0402JRNPO9BN101")
    (property "Description" "YAGEO - CC0402JRNPO9BN101 - SMD Multilayer Ceramic Capacitor, 100 pF, 50 V, 0402 [1005 Metric], +/- 5%, C0G / NP0, CC Series")
    (property "Datasheet_Link" "https://ad.componentsearchengine.com/Datasheets/2/CC0402JRNPO9BN101.pdf")
    (property "symbolName1" "CC0402JRNPO9BN101")
)
