(part "MIC23303YML-TR"
    (packageRef "SON50P300X300X90-13N-D")
    (interface
        (port "1" (symbPinId 1) (portName "SW_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SW_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PG") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SNS") (portType INOUT))
        (port "6" (symbPinId 6) (portName "FB") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SS") (portType INOUT))
        (port "8" (symbPinId 8) (portName "AGND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "AVIN") (portType INOUT))
        (port "10" (symbPinId 10) (portName "PVIN_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "PVIN_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "PGND") (portType INOUT))
        (port "13" (symbPinId 13) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "998-MIC23303YMLTR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology-Micrel/MIC23303YML-TR?qs=Y3Q3JoKAO1Rutw%2FCoJCU2w%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MIC23303YML-TR")
    (property "Description" "Conv DC-DC 2.7V to 5.5V Synchronous Step Down Single-Out 0.65V to 3.6V 3A 12-Pin DFN EP T/R")
    (property "Datasheet_Link" "http://www.microchip.com/mymicrochip/filehandler.aspx?ddocname=en580343")
    (property "symbolName1" "MIC23303YML-TR")
)
