(part "MAX8510EXK29+T"
    (packageRef "SOT65P210X110-5N")
    (interface
        (port "1" (symbPinId 1) (portName "IN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%SHDN%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "BP") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "700-MAX8510EXK29T")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Maxim-Integrated/MAX8510EXK29%2bT?qs=Jw2w9zrI6w%252BbZa1dXLYLrw%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "MAX8510EXK29+T")
    (property "Description" "Fixed LDO Voltage Regulator, 2V-6V in, 135mV Dropout, 2.85V/120mA out, SC-70-5")
    (property "Datasheet_Link" "https://www.analog.com/media/en/technical-documentation/data-sheets/max8510-max8512.pdf")
    (property "symbolName1" "MAX8510EXK29+T")
)
