(part "SMBJ5_0A-TR"
    (packageRef "SMBJ12A")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-SMBJ5.0A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/SMBJ5.0A-TR?qs=QR0jAJXDF2ih8aaSsBQmUg%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "SMBJ5.0A-TR")
    (property "Description" "ESD Suppressors / TVS Diodes 600W 5.0V Unidirect")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/smbj58ca.pdf")
    (property "symbolName1" "SMBJ5_0A-TR")
)
