(part "RC0402FR-0720KL"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "603-RC0402FR-0720KL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/RC0402FR-0720KL?qs=V1yeUXFNrklxRvgYM5JI2A%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "RC0402FR-0720KL")
    (property "Description" "Thick Film Resistors - SMD 20 kOhms 62.5mW 0402 1%")
    (property "Datasheet_Link" "https://www.yageo.com/upload/media/product/productsearch/datasheet/rchip/PYu-RC_Group_51_RoHS_L_12.pdf")
    (property "symbolName1" "RC0402FR-0720KL")
)
