(part "TCA9517DGKRQ1"
    (packageRef "SOP65P490X110-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VCCA") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SCLA") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SDAA") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SDAB") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SCLB") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCCB") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TCA9517DGKRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TCA9517DGKRQ1?qs=%252BEew9%252B0nqrBZmTVyzm%252B7dQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TCA9517DGKRQ1")
    (property "Description" "Automotive, Level-Shifting I2C Bus Repeater")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tca9517-q1")
    (property "symbolName1" "TCA9517DGKRQ1")
)
