(part "CC0603KRX5R6BB475"
    (packageRef "CAPC1608X90N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "603-CC603KRX5R6BB475")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Yageo/CC0603KRX5R6BB475/?qs=BKNoF%2F0xMNun51HoEirUUw%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "CC0603KRX5R6BB475")
    (property "Description" "YAGEO (PHYCOMP) - CC0603KRX5R6BB475 - CAP, MLCC, X5R, 4.7UF, 10V, 0603")
    (property "Datasheet_Link" "")
    (property "symbolName1" "CC0603KRX5R6BB475")
)
