(part "BCM857BS-7-F"
    (packageRef "SOT65P210X110-6N")
    (interface
        (port "1" (symbPinId 1) (portName "E1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "B1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "E2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "B2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "C1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "621-BCM857BS-7-F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/BCM857BS-7-F?qs=60RJRzIpcl83Pda4UUWqGw%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "BCM857BS-7-F")
    (property "Description" "Bipolar Transistors - BJT 45V Matched Pair PNP Bvceo -45V -100mA")
    (property "Datasheet_Link" "")
    (property "symbolName1" "BCM857BS-7-F")
)
