(part "RC0402FR-07124KL"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "603-RC0402FR-07124KL")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=603-RC0402FR-07124KL")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "RC0402FR-07124KL")
    (property "Description" "RESISTOR, 0402 124K Ohms +/-1% 1/16 W")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/RC0402FR-07124KL.pdf")
    (property "symbolName1" "RC0402FR-07124KL")
)
