(part "CC0201KRX5R6BB104"
    (packageRef "CAPC0603X35N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "603-CC201KRX5R6BB104")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/CC0201KRX5R6BB104?qs=vCz78MyBKmpx%252BntAJRyVZA%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "CC0201KRX5R6BB104")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT 10 V 0.1uF X5R 0201 10%")
    (property "Datasheet_Link" "")
    (property "symbolName1" "CC0201KRX5R6BB104")
)
