SamacSys ECAD Model
318370/1743273/2.50/2/2/Inductor

DESIGNSPARK_INTERMEDIATE_ASCII

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r150_70"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 0.700) (shapeHeight 1.500))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Default"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 50 mils)
			(strokeWidth 5 mils)
		)
	)
	(patternDef "LQM2HPN1R0MG0L" (originalName "LQM2HPN1R0MG0L")
		(multiLayer
			(pad (padNum 1) (padStyleRef r150_70) (pt -1.150, 0.000) (rotation 0))
			(pad (padNum 2) (padStyleRef r150_70) (pt 1.150, 0.000) (rotation 0))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt 0.000, 0.000) (textStyleRef "Default") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1.25 1) (pt 1.25 1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt 1.25 1) (pt 1.25 -1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt 1.25 -1) (pt -1.25 -1) (width 0.1))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1.25 -1) (pt -1.25 1) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt -2.5 2) (pt 2.5 2) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt 2.5 2) (pt 2.5 -2) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt 2.5 -2) (pt -2.5 -2) (width 0.1))
		)
		(layerContents (layerNumRef 30)
			(line (pt -2.5 -2) (pt -2.5 2) (width 0.1))
		)
		(layerContents (layerNumRef 18)
			(line (pt 0 1) (pt 0 -1) (width 0.1))
		)
	)
	(symbolDef "LQM2HPN4R7MG0L" (originalName "LQM2HPN4R7MG0L")

		(pin (pinNum 1) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName false)) (pinName (text (pt 0 mils -35 mils) (rotation 0]) (justify "UpperLeft") (textStyleRef "Default"))
		))
		(pin (pinNum 2) (pt 800 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName false)) (pinName (text (pt 800 mils -35 mils) (rotation 0]) (justify "UpperRight") (textStyleRef "Default"))
		))
		(arc (pt 250 mils -2 mils) (radius 50 mils) (startAngle 177.7) (sweepAngle -175.4) (width 6 mils))
		(arc (pt 350 mils -2 mils) (radius 50 mils) (startAngle 177.7) (sweepAngle -175.4) (width 6 mils))
		(arc (pt 450 mils -2 mils) (radius 50 mils) (startAngle 177.7) (sweepAngle -175.4) (width 6 mils))
		(arc (pt 550 mils -2 mils) (radius 50 mils) (startAngle 177.7) (sweepAngle -175.4) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 650 mils 250 mils) (justify Left) (isVisible True) (textStyleRef "Default"))

	)
	(compDef "LQM2HPN4R7MG0L" (originalName "LQM2HPN4R7MG0L") (compHeader (numPins 2) (numParts 1) (refDesPrefix L)
		)
		(compPin "1" (pinName "1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "2" (pinName "2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "LQM2HPN4R7MG0L"))
		(attachedPattern (patternNum 1) (patternName "LQM2HPN1R0MG0L")
			(numPads 2)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
			)
		)
		(attr "Mouser Part Number" "81-LQM2HPN4R7MG0L")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/LQM2HPN4R7MG0L?qs=%2F%252BYoplLUB5jnkqM2%2FFTc3g%3D%3D")
		(attr "Manufacturer_Name" "Murata Electronics")
		(attr "Manufacturer_Part_Number" "LQM2HPN4R7MG0L")
		(attr "Description" "Inductor SMD 1008 shielded 4.7uH Murata LQM2HP_G0 Series 4700 nH +/-20% Ferrite Multilayer SMD Inductor, 1008 Case, SRF: 0.025GHz 1.1A dc 138m Rdc")
		(attr "Datasheet Link" "https://search.murata.co.jp/Ceramy/image/img/P02/JELF243B-0019.pdf")
		(attr "Height" "1 mm")
	)

)
