---
HSS:
    type: git
    link: https://openbeagle.org/beaglev-fire/hart-software-services.git
    branch: main-beaglev-fire
    board: bvf
gateware:
    type: sources
    unique-design-version: 2.0.4

