(part "CC0402KRX7R9BB103"
    (packageRef "CAPC1005X55N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "603-CC402KRX7R9BB103")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/CC0402KRX7R9BB103?qs=rEZiXmXGZa%252BpBmDCpwG%252B9w%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "CC0402KRX7R9BB103")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT 50V 0.01uF X7R 0402 10%")
    (property "Datasheet_Link" "https://www.yageo.com/upload/media/product/productsearch/datasheet/mlcc/UPY-GPHC_X7R_6.3V-to-250V_23.pdf")
    (property "symbolName1" "CC0402KRX7R9BB103")
)
