(part "TMP112AQDRLRQ1"
    (packageRef "SOTFL50P160X60-6N")
    (interface
        (port "1" (symbPinId 1) (portName "SCL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "ALERT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "ADD0") (portType INOUT))
        (port "5" (symbPinId 5) (portName "V+") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SDA") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TMP112AQDRLRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TMP112AQDRLRQ1?qs=asCBFxFfL1Q5YmJCm%252BGnCQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TMP112AQDRLRQ1")
    (property "Description" "Automotive Grade, 1.4V-Capable +/-0.5C Temperature Sensor with Alert Function and I2C/SMBus")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tmp112-q1")
    (property "symbolName1" "TMP112AQDRLRQ1")
)
