(part "RC0402FR-072K7L"
    (packageRef "RESC1005X40N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "603-RC0402FR-072K7L")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Yageo/RC0402FR-072K7L?qs=UOUeRUa%252B8Wlu89tUHFnI0g%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "RC0402FR-072K7L")
    (property "Description" "RESISTOR, 0402 2.7K Ohms +/-1% 1/16 W")
    (property "Datasheet_Link" "http://www.yageo.com/documents/recent/PYu-RC0402_51_RoHS_L_6_r.pdf")
    (property "symbolName1" "RC0402FR-072K7L")
)
