(part "SKRPABE010"
    (packageRef "SKRPABE010")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "688-SKRPAB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Alps-Alpine/SKRPABE010?qs=m0BA540hBPe1GpcSf%2FZ5Yw%3D%3D")
    (property "Manufacturer_Name" "ALPS Electric")
    (property "Manufacturer_Part_Number" "SKRPABE010")
    (property "Description" "Switch Tactile N.O. SPST Button J-Bend 0.05A 16VDC 1.57N SMD Automotive T/R")
    (property "Datasheet_Link" "https://tech.alpsalpine.com/e/products/detail/SKRPABE010/")
    (property "symbolName1" "SKRPABE010")
)
