(part "CC0805MKX5R8BB226"
    (packageRef "CAPC2012X145N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "603-CC805MKX5R8BB226")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/YAGEO/CC0805MKX5R8BB226?qs=WS5Jv%252B%252Bx1qULWDK6O%2FQuig%3D%3D")
    (property "Manufacturer_Name" "Yageo Group")
    (property "Manufacturer_Part_Number" "CC0805MKX5R8BB226")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT 25 V 22 uF X5R 0805 20%")
    (property "Datasheet_Link" "https://www.yageo.com/upload/media/product/productsearch/datasheet/mlcc/UPY-GPHC_X5R_4V-to-50V_26.pdf")
    (property "symbolName1" "CC0805MKX5R8BB226")
)
