(part "TPS2051CDBVR"
    (packageRef "SOT95P280X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "%FLT%") (portType INOUT))
        (port "4" (symbPinId 4) (portName "EN/%EN%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS2051CDBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS2051CDBVR?qs=PF3AD18CSE5vi2HeWLJCmw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS2051CDBVR")
    (property "Description" "Single Channel, Current-Limited USB Power Distribution Switch")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/tps2051c")
    (property "symbolName1" "TPS2051CDBVR")
)
